language: node_js
sudo: false
node_js:
- '0.10'
deploy:
- provider: opsworks
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key:
    secure: QDekpK87BkLanL1OK34qQPuaU+f5QH5Fv442DWLVtBFFC/01J+kxxow3P0rcO1rjcBTUKR4FJl5a55LMKOPwczCgEdUbreJ/vckDJuO5CSflq8ljxW6CedJCQk0BQ5wcdTWHLeS7wvs8RVcnT3krxPHy+wGOBTDeSBMs43BRveg=
  app-id: 3d6a16ba-bb46-45ff-924c-ca05dbfc009f
  on:
    branch: master
- provider: opsworks
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key:
    secure: QDekpK87BkLanL1OK34qQPuaU+f5QH5Fv442DWLVtBFFC/01J+kxxow3P0rcO1rjcBTUKR4FJl5a55LMKOPwczCgEdUbreJ/vckDJuO5CSflq8ljxW6CedJCQk0BQ5wcdTWHLeS7wvs8RVcnT3krxPHy+wGOBTDeSBMs43BRveg=
  app-id: 1541e904-cf87-40e5-9f27-3bdbbf1544c2
  on:
    branch: staging
