language: node_js
use_sudo: false
node_js:
- '0.10'
deploy:
  provider: opsworks
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key:
    secure: Hh1kaYc/gefbZra9SYHnK6y27vtbAhiaRxPt+ov82ZYduCAUZXk3ScoMWcLtTsuFhSa0nlWhfDklelZgMU4Q7WwEwn0RK3k+4EHIjlJrjn+WsAWQEGrb1XphufhIw665+h+dpaojfDDu75OOAc/k8OwoEhr4+MhKw7kwJqUc9e4=
  app-id: 4b65ba59-f39f-40bf-88d0-93087cacb884
  on:
    branch: master
