language: node_js
sudo: false
node_js:
- '0.10'
deploy:
  provider: npm
  email: sqrt@octoblu.com
  api_key:
    secure: z8QyaAeU7KTPOaEQJu2LkoYF1FYsy5sWjqVfsuWn2n7TzJKzq0Io2qr9gcSKu/x19kKsAR+Jc2kmoNMxdy9TgHzA7GwIzMFTjxgAGk0tdv+ro8o/qliiGKXk16q0Q5JvS7pd6YhnE8SfUtq0WslOuzP1lINWu/a3YqLn1Z2LR4g=
  on:
    tags: true
    repo: octoblu/meshblu-email-password-authenticator
